baseURL = 'https://jerrybrown5.github.io/toddler-reading-blog/'
languageCode = 'en-us'
title = 'Toddler Reading Blog'
theme = "PaperMod"

# Tell Hugo to skip the broken RSS template for now
disableKinds = ["RSS"]

# The new standard way Hugo handles theme parameters
[params]
  author = "Jerry Brown"
  ShowReadingTime = true
  ShowPostNavLinks = true

  [params.homeInfoParams]
    Title = "Toddler Reading Blog"
    Content = "A parent's guide to teaching young children to read â€” practical tips, real experiences, and what actually works."

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/jerrybrown5"

